"""Orchestrates one AI analysis run and persists every artefact it produces.

Pipeline: retrieve -> generate -> extract claims -> validate evidence ->
detect contradictions -> compute metrics -> persist -> audit.

Each stage writes its own audit event, so the trail reconstructs what the
system did, in order, with what inputs.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from src.assurance.claim_extractor import extract_claims
from src.assurance.contradiction_detector import detect_contradictions, llm_contradiction_pass
from src.assurance.evidence_validator import EvidenceValidator
from src.assurance.metrics import acceptance_score, compute_metrics
from src.assurance.recommendation_engine import synthesize
from src.audit.logger import EventType, log_ai_event, log_event
from src.database.db import session_scope
from src.database.models import AIAnalysis
from src.database.repositories import AnalysisRepository, CaseRepository, ReviewRepository
from src.llm.provider import LLMError, LLMProvider, get_llm_provider
from src.llm.summarizer import generate_case_analysis
from src.models.schemas import (
    AnalysisBundle,
    AssuranceMetrics,
    AssuranceStatus,
    CaseAnalysisOutput,
    CaseStatus,
    ClaimType,
    ContradictionFlag,
    EvidenceLink,
    FinalCaseAssessment,
    RetrievedChunk,
    ValidatedClaim,
)
from src.retrieval.retriever import Retriever

logger = logging.getLogger(__name__)


class AnalysisError(RuntimeError):
    """Raised when an analysis cannot be produced."""


def run_analysis(
    case_id: str,
    *,
    provider: Optional[LLMProvider] = None,
    retriever: Optional[Retriever] = None,
) -> AnalysisBundle:
    with session_scope() as session:
        case = CaseRepository.get(session, case_id)
        if case is None:
            raise AnalysisError(f"Case {case_id} was not found.")
        case_number, applicant_name, slug = case.case_number, case.applicant_name, case.slug

    provider = provider or get_llm_provider()
    retriever = retriever or Retriever()

    log_ai_event(
        EventType.ANALYSIS_REQUESTED,
        f"AI analysis requested for {case_number}",
        case_id=case_id,
        metadata={"provider": provider.name, "model": provider.model, "demo_mode": provider.is_demo},
    )

    try:
        generation = generate_case_analysis(
            case_id, case_number, applicant_name, slug, retriever=retriever, provider=provider
        )
    except LLMError as exc:
        log_event(
            EventType.ERROR,
            f"Analysis failed: {exc}",
            case_id=case_id,
            metadata={"stage": "generation", "provider": provider.name},
        )
        raise AnalysisError(str(exc)) from exc

    log_ai_event(
        EventType.EVIDENCE_RETRIEVED,
        f"{len(generation.retrieved_chunks)} evidence chunks retrieved",
        case_id=case_id,
        metadata={
            "chunks": len(generation.retrieved_chunks),
            "source_ids": generation.retrieved_source_ids,
            "documents": len({c.document_id for c in generation.retrieved_chunks}),
        },
    )
    log_ai_event(
        EventType.SUMMARY_GENERATED,
        f"Summary generated by {generation.model_name}",
        case_id=case_id,
        metadata={
            "model": generation.model_name,
            "provider": generation.provider_name,
            "prompt_version": generation.prompt_version,
            "system_prompt_version": generation.system_prompt_version,
            "latency_ms": generation.latency_ms,
            "demo_mode": generation.demo_mode,
        },
    )

    raw_claims = extract_claims(generation.output, provider)
    log_ai_event(
        EventType.CLAIMS_EXTRACTED,
        f"{len(raw_claims)} claims extracted",
        case_id=case_id,
        metadata={"claims": len(raw_claims)},
    )

    validator = EvidenceValidator(retriever=retriever, provider=provider)
    validated = validator.validate_all(raw_claims, case_id, generation.retrieved_chunks)

    # Contradiction detection runs over the *whole* case record, not just the
    # passages retrieved for the summary. Two documents disagreeing is a property
    # of the file, not of what a retrieval pass happened to surface — and once
    # history events share the index, a top-k pool can no longer be assumed to
    # hold both sides of a conflict.
    all_chunks = retriever.all_chunks(case_id)
    contradictions = detect_contradictions(all_chunks)
    contradictions.extend(_model_declared_conflicts(generation.output, all_chunks))
    if not provider.is_demo:  # pragma: no cover - network path
        contradictions.extend(llm_contradiction_pass(provider, generation.retrieved_chunks))

    assessment = synthesize(generation.output, validated, contradictions)
    metrics = compute_metrics(validated, contradictions)

    counts = {
        status.value: sum(1 for c in validated if c.assurance_status == status)
        for status in AssuranceStatus
    }
    log_ai_event(
        EventType.CLAIMS_VALIDATED,
        (
            f"{counts[AssuranceStatus.SUPPORTED.value]} supported, "
            f"{counts[AssuranceStatus.WEAK_SUPPORT.value]} weakly supported, "
            f"{counts[AssuranceStatus.UNSUPPORTED.value]} unsupported, "
            f"{counts[AssuranceStatus.CONTRADICTED.value]} contradicted"
        ),
        case_id=case_id,
        metadata=counts,
    )
    if counts[AssuranceStatus.UNSUPPORTED.value]:
        log_ai_event(
            EventType.UNSUPPORTED_CLAIM_DETECTED,
            f"{counts[AssuranceStatus.UNSUPPORTED.value]} unsupported claim(s) flagged for human verification",
            case_id=case_id,
            metadata={
                "claims": [
                    c.claim_text
                    for c in validated
                    if c.assurance_status == AssuranceStatus.UNSUPPORTED
                ]
            },
        )
    if contradictions:
        log_ai_event(
            EventType.CONTRADICTION_DETECTED,
            f"{len(contradictions)} potential contradiction(s) requiring human review",
            case_id=case_id,
            metadata={"fields": [f.conflicting_field for f in contradictions]},
        )

    log_ai_event(
        EventType.OVERALL_RECOMMENDATION_GENERATED,
        (
            f"Recommendation: {assessment.overall_recommendation.display} "
            f"({assessment.recommendation_confidence:.0%} confidence, "
            f"{assessment.material_unresolved_issues} material unresolved issue"
            f"{'' if assessment.material_unresolved_issues == 1 else 's'})"
        ),
        case_id=case_id,
        metadata={
            "model": generation.model_name,
            "prompt_version": generation.prompt_version,
            "recommendation": assessment.overall_recommendation.value,
            "model_proposed_recommendation": (
                assessment.model_proposed_recommendation.value
                if assessment.model_proposed_recommendation
                else None
            ),
            "model_agreed_with_engine": assessment.model_agreed_with_engine,
            "concern_level": assessment.overall_concern_level.value,
            "confidence": assessment.recommendation_confidence,
            "material_unresolved_issues": assessment.material_unresolved_issues,
            "reasons": len(assessment.why_this_recommendation),
            "evidence_used": sorted(
                {
                    link.source_id
                    for reason in assessment.why_this_recommendation
                    for link in reason.evidence
                }
            ),
            "engine_rationale": assessment.engine_rationale,
        },
    )

    previous = load_latest_assessment(case_id)
    if previous and previous.overall_recommendation != assessment.overall_recommendation:
        log_ai_event(
            EventType.RECOMMENDATION_CHANGED,
            (
                f"Recommendation changed from {previous.overall_recommendation.display} to "
                f"{assessment.overall_recommendation.display} after the evidence was re-evaluated"
            ),
            case_id=case_id,
            metadata={
                "from": previous.overall_recommendation.value,
                "to": assessment.overall_recommendation.value,
                "engine_rationale": assessment.engine_rationale,
            },
        )

    analysis_id = _persist(
        case_id=case_id,
        generation=generation,
        validated=validated,
        contradictions=contradictions,
        metrics=metrics,
        assessment=assessment,
    )

    log_ai_event(
        EventType.METRICS_COMPUTED,
        (
            f"Groundedness {metrics.groundedness:.0%}, evidence coverage "
            f"{metrics.evidence_coverage:.0%}, unsupported rate {metrics.unsupported_claim_rate:.0%}"
        ),
        case_id=case_id,
        analysis_id=analysis_id,
        metadata=metrics.model_dump(),
    )

    return AnalysisBundle(
        analysis_id=analysis_id,
        case_id=case_id,
        case_number=case_number,
        model_name=generation.model_name,
        prompt_version=generation.prompt_version,
        generated_at=_generated_at(analysis_id),
        latency_ms=generation.latency_ms,
        demo_mode=generation.demo_mode,
        output=generation.output,
        claims=validated,
        contradictions=contradictions,
        metrics=metrics,
        assessment=assessment,
        retrieved_chunks=generation.retrieved_chunks,
    )


def _model_declared_conflicts(
    output: CaseAnalysisOutput, chunks: List[RetrievedChunk]
) -> List[ContradictionFlag]:
    """Surface conflicts the model itself declared, kept separate from heuristics."""
    by_source = {chunk.source_id: chunk for chunk in chunks}
    flags: List[ContradictionFlag] = []
    for conflict in output.potential_conflicts:
        sources = [by_source[s] for s in conflict.source_ids if s in by_source]
        first = sources[0] if sources else None
        second = sources[1] if len(sources) > 1 else first
        flags.append(
            ContradictionFlag(
                conflicting_field=conflict.conflicting_field,
                description=f"Potential contradiction requiring human review: {conflict.description}",
                source_a_id=first.source_id if first else "",
                source_a_document=first.document_name if first else "Not cited",
                source_a_text=first.content[:400] if first else "",
                source_b_id=second.source_id if second else "",
                source_b_document=second.document_name if second else "Not cited",
                source_b_text=second.content[:400] if second else "",
                confidence=0.6,
                detector="model-declared",
            )
        )
    return flags


def _persist(
    *,
    case_id: str,
    generation,
    validated: List[ValidatedClaim],
    contradictions: List[ContradictionFlag],
    metrics: AssuranceMetrics,
    assessment: FinalCaseAssessment,
) -> str:
    with session_scope() as session:
        analysis = AnalysisRepository.create(
            session,
            case_id=case_id,
            model_name=generation.model_name,
            prompt_version=generation.prompt_version,
            demo_mode=generation.demo_mode,
            latency_ms=generation.latency_ms,
            generated_summary=generation.output.executive_summary,
            raw_output=generation.output.model_dump(mode="json"),
            retrieved_source_ids=generation.retrieved_source_ids,
            assessment=assessment.model_dump(mode="json"),
            recommendation=assessment.overall_recommendation.value,
            recommendation_confidence=assessment.recommendation_confidence,
            concern_level=assessment.overall_concern_level.value,
            material_unresolved_issues=assessment.material_unresolved_issues,
        )
        for index, claim in enumerate(validated):
            row = AnalysisRepository.add_claim(
                session,
                analysis_id=analysis.id,
                claim_index=index,
                claim_text=claim.claim_text,
                claim_type=claim.claim_type.value,
                assurance_status=claim.assurance_status.value,
                confidence_score=claim.confidence_score,
                semantic_score=claim.semantic_score,
                retrieval_score=claim.retrieval_score,
                entailment_score=claim.entailment_score,
                model_confidence=claim.model_confidence,
                rationale=claim.rationale,
            )
            for link in claim.evidence:
                AnalysisRepository.add_evidence(
                    session,
                    claim_id=row.id,
                    document_id=link.document_id,
                    chunk_id=link.chunk_id,
                    source_id=link.source_id,
                    source_type=link.source_type.value,
                    document_ref=link.document_ref,
                    document_date=link.document_date,
                    event_id=link.event_id,
                    event_date=link.event_date,
                    event_type=link.event_type,
                    document_name=link.document_name,
                    evidence_text=link.evidence_text,
                    relevance_score=link.relevance_score,
                    cited_by_model=link.cited_by_model,
                )
        for flag in contradictions:
            AnalysisRepository.add_contradiction(
                session,
                analysis_id=analysis.id,
                case_id=case_id,
                **flag.model_dump(),
            )
        AnalysisRepository.add_metrics(
            session, analysis_id=analysis.id, case_id=case_id, **metrics.model_dump()
        )
        CaseRepository.set_status(session, case_id, CaseStatus.AWAITING_REVIEW.value)
        return analysis.id


def _generated_at(analysis_id: str):
    with session_scope() as session:
        analysis = session.get(AIAnalysis, analysis_id)
        return analysis.generated_at


# ---------------------------------------------------------------------------
# Read path
# ---------------------------------------------------------------------------
def load_latest_assessment(case_id: str) -> Optional[FinalCaseAssessment]:
    """The most recent shipped recommendation for a case, if any."""
    with session_scope() as session:
        analysis = AnalysisRepository.latest_for_case(session, case_id)
        if analysis is None or not analysis.assessment:
            return None
        try:
            return FinalCaseAssessment.model_validate(analysis.assessment)
        except Exception:  # noqa: BLE001 - a stale row must not block a new run
            return None


def load_analysis(analysis_id: str) -> Optional[AnalysisBundle]:
    with session_scope() as session:
        analysis = AnalysisRepository.get(session, analysis_id)
        if analysis is None:
            return None
        case = CaseRepository.get(session, analysis.case_id)
        return _to_bundle(session, analysis, case.case_number if case else "")


def load_latest_analysis(case_id: str) -> Optional[AnalysisBundle]:
    with session_scope() as session:
        analysis = AnalysisRepository.latest_for_case(session, case_id)
        if analysis is None:
            return None
        case = CaseRepository.get(session, case_id)
        return _to_bundle(session, analysis, case.case_number if case else "")


def _to_bundle(session, analysis: AIAnalysis, case_number: str) -> AnalysisBundle:
    metrics_row = AnalysisRepository.metrics_for_analysis(session, analysis.id)
    review = ReviewRepository.latest_for_analysis(session, analysis.id)

    metrics = (
        AssuranceMetrics(
            groundedness=metrics_row.groundedness,
            evidence_coverage=metrics_row.evidence_coverage,
            unsupported_claim_rate=metrics_row.unsupported_claim_rate,
            contradiction_rate=metrics_row.contradiction_rate,
            source_diversity=metrics_row.source_diversity,
            total_claims=metrics_row.total_claims,
            supported_claims=metrics_row.supported_claims,
            weak_claims=metrics_row.weak_claims,
            unsupported_claims=metrics_row.unsupported_claims,
            contradicted_claims=metrics_row.contradicted_claims,
            reviewer_acceptance=acceptance_score(review.decision) if review else None,
        )
        if metrics_row
        else AssuranceMetrics()
    )

    claims = [
        ValidatedClaim(
            claim_text=row.claim_text,
            claim_type=ClaimType(row.claim_type),
            assurance_status=AssuranceStatus(row.assurance_status),
            confidence_score=row.confidence_score,
            semantic_score=row.semantic_score,
            retrieval_score=row.retrieval_score,
            entailment_score=row.entailment_score,
            model_confidence=row.model_confidence,
            rationale=row.rationale,
            evidence=[
                EvidenceLink(
                    source_id=link.source_id,
                    chunk_id=link.chunk_id,
                    case_id=analysis.case_id,
                    source_type=link.source_type or "document",
                    document_id=link.document_id,
                    document_ref=link.document_ref,
                    document_name=link.document_name,
                    document_date=link.document_date,
                    event_id=link.event_id,
                    event_date=link.event_date,
                    event_type=link.event_type,
                    evidence_text=link.evidence_text,
                    relevance_score=link.relevance_score,
                    cited_by_model=link.cited_by_model,
                )
                for link in sorted(row.evidence, key=lambda e: e.relevance_score, reverse=True)
            ],
        )
        for row in sorted(analysis.claims, key=lambda c: c.claim_index)
    ]

    contradictions = [
        ContradictionFlag(
            conflicting_field=row.conflicting_field,
            description=row.description,
            source_a_id=row.source_a_id,
            source_a_document=row.source_a_document,
            source_a_text=row.source_a_text,
            source_b_id=row.source_b_id,
            source_b_document=row.source_b_document,
            source_b_text=row.source_b_text,
            confidence=row.confidence,
            detector=row.detector,
        )
        for row in analysis.contradictions
    ]

    stored_assessment = analysis.assessment or {}
    assessment = (
        FinalCaseAssessment.model_validate(stored_assessment)
        if stored_assessment
        else FinalCaseAssessment()
    )

    raw: Dict[str, Any] = analysis.raw_output or {}
    output = (
        CaseAnalysisOutput.model_validate(raw)
        if raw
        else CaseAnalysisOutput(executive_summary=analysis.generated_summary)
    )

    return AnalysisBundle(
        analysis_id=analysis.id,
        case_id=analysis.case_id,
        case_number=case_number,
        model_name=analysis.model_name,
        prompt_version=analysis.prompt_version,
        generated_at=analysis.generated_at,
        latency_ms=analysis.latency_ms,
        demo_mode=analysis.demo_mode,
        output=output,
        claims=claims,
        contradictions=contradictions,
        metrics=metrics,
        assessment=assessment,
        retrieved_chunks=[],
    )
